import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import process from 'node:process';

const generatedDir = process.env.NGINX_GENERATED_DIR || '/etc/nginx/generated/conf.d';
const certDir = process.env.NGINX_CERT_DIR || '/etc/nginx/certs';
const pidFile = process.env.NGINX_PID_FILE || '/etc/nginx/runtime/nginx.pid';
const portMin = Number(process.env.PUBLIC_PORT_MIN || 8080);
const portMax = Number(process.env.PUBLIC_PORT_MAX || 8099);
const tlsPortMin = Number(process.env.PUBLIC_TLS_PORT_MIN || 8443);
const tlsPortMax = Number(process.env.PUBLIC_TLS_PORT_MAX || 8459);

export function validatePort(port) {
  const parsed = Number(port);
  const inHttpRange = parsed >= portMin && parsed <= portMax;
  const inTlsRange = parsed >= tlsPortMin && parsed <= tlsPortMax;

  if (!Number.isInteger(parsed) || (!inHttpRange && !inTlsRange)) {
    throw new Error(`Port must be in ${portMin}-${portMax} or ${tlsPortMin}-${tlsPortMax}.`);
  }

  return parsed;
}

export function validateEndpoint(endpoint) {
  let url;
  try {
    url = new URL(endpoint);
  } catch {
    throw new Error('Endpoint must be a valid http:// or https:// URL.');
  }

  if (!['http:', 'https:'].includes(url.protocol)) {
    throw new Error('Endpoint must use http:// or https://.');
  }

  return url;
}

function escapeNginxValue(value) {
  return String(value).replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '');
}

function normalizeHeaders(headers) {
  if (!headers || typeof headers !== 'object' || Array.isArray(headers)) return {};
  return Object.fromEntries(
    Object.entries(headers)
      .filter(([key, value]) => /^[A-Za-z0-9-]+$/.test(key) && value !== undefined && value !== null)
      .map(([key, value]) => [key, String(value)])
  );
}

function upstreamFor(endpoint) {
  const url = validateEndpoint(endpoint);
  const base = `${url.protocol}//${url.host}${url.pathname.endsWith('/') ? url.pathname : `${url.pathname}/`}`;
  return {
    base,
    host: url.host,
  };
}

function sslBlock(activeCertificate, port) {
  const isTlsPort = port >= tlsPortMin && port <= tlsPortMax;
  if (!activeCertificate || !isTlsPort) return { listen: `listen ${port};`, ssl: '' };

  return {
    listen: `listen ${port} ssl;`,
    ssl: `
  ssl_certificate /etc/nginx/certs/current/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/current/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;`,
  };
}

function normalProxyConfig(rule, activeCertificate) {
  const upstream = upstreamFor(rule.endpoint);
  const headers = normalizeHeaders(rule.headers);
  const tls = sslBlock(activeCertificate, rule.public_port);
  const customHeaders = Object.entries(headers)
    .map(([key, value]) => `    proxy_set_header ${key} "${escapeNginxValue(value)}";`)
    .join('\n');

  return `# Generated by nginx-proxy-manager-api. Do not edit by hand.
server {
  ${tls.listen}
  server_name _;
${tls.ssl}

  location / {
    proxy_ssl_server_name on;
    proxy_set_header Host ${upstream.host};
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
${customHeaders ? `${customHeaders}\n` : ''}    proxy_pass ${upstream.base};
  }
}
`;
}

function mcpProxyConfig(rule, activeCertificate) {
  const tls = sslBlock(activeCertificate, rule.public_port);

  return `# Generated by nginx-proxy-manager-api. Do not edit by hand.
server {
  ${tls.listen}
  server_name _;
${tls.ssl}

  location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    rewrite ^.*$ /mcp-proxy/${rule.id} break;
    proxy_pass http://api:4000;
  }
}
`;
}

export async function renderAllRules(rules, activeCertificate) {
  await fs.mkdir(generatedDir, { recursive: true });
  const existing = await fs.readdir(generatedDir).catch(() => []);

  await Promise.all(
    existing
      .filter((file) => file.endsWith('.conf'))
      .map((file) => fs.rm(path.join(generatedDir, file), { force: true }))
  );

  await Promise.all(
    rules
      .filter((rule) => rule.enabled)
      .map((rule) => {
        const body = rule.mcp_enabled
          ? mcpProxyConfig(rule, activeCertificate)
          : normalProxyConfig(rule, activeCertificate);
        return fs.writeFile(path.join(generatedDir, `rule-${rule.public_port}-${rule.id}.conf`), body);
      })
  );
}

export async function writeCertificateFiles(files) {
  const currentDir = path.join(certDir, 'current');
  await fs.mkdir(currentDir, { recursive: true });

  const certificate = await fs.readFile(files.certificate[0].path, 'utf8');
  const privateKey = await fs.readFile(files.privateKey[0].path, 'utf8');
  const caBundle = files.caBundle ? await fs.readFile(files.caBundle[0].path, 'utf8') : '';
  const fullchain = caBundle ? `${certificate.trim()}\n${caBundle.trim()}\n` : certificate;

  await fs.writeFile(path.join(currentDir, 'fullchain.pem'), fullchain, { mode: 0o644 });
  await fs.writeFile(path.join(currentDir, 'privkey.pem'), privateKey, { mode: 0o600 });

  if (caBundle) {
    await fs.writeFile(path.join(currentDir, 'ca_bundle.pem'), caBundle, { mode: 0o644 });
  }

  return {
    certificatePath: '/etc/nginx/certs/current/fullchain.pem',
    privateKeyPath: '/etc/nginx/certs/current/privkey.pem',
    caBundlePath: caBundle ? '/etc/nginx/certs/current/ca_bundle.pem' : null,
    fingerprint: crypto.createHash('sha256').update(certificate).digest('hex'),
  };
}

export async function reloadNginx() {
  const pidText = await fs.readFile(pidFile, 'utf8');
  const pid = Number(pidText.trim());
  if (!Number.isInteger(pid) || pid < 1) {
    throw new Error('Nginx PID file did not contain a valid process id.');
  }
  process.kill(pid, 'SIGHUP');
}
